spring.application.name=SpringBoot-PMS

#embedded tomcat port number
server.port=1234

#Database connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/coforge
spring.datasource.username=root
spring.datasource.password=Password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Application Properties
pms.save.success="SUCCESS : Product Details Inserted"

pms.db.failed="FAILED : DB Error"

pms.save.fail="FAILED : Invalid Product Details"

pms.update.success="SUCCESS : Product Object Updated"

pms.delete.success="SUCCESS : Product Object Deleted"

pms.find.success="SUCCESS : Product Details Found"

pms.invalid.product-details="FAILED : Invalid Product Details"

pms.invalid.product-notfound="FAILED : Product Details not found"

eureka.instance.hostname=localhost

#Stop registering as a client. It is a Server
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true