spring.application.name=SB-MSA-ServiceRegistry
#Port number for service registry
server.port=8761

eureka.instance.hostname=localhost

#Stop registering as a client. It is a Server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
